import os
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.environ.get("GOOGLE_API_KEY")
API_KEY_2 = os.environ.get("GOOGLE_API_KEY_2")
MAX_IMAGE_SIZE_MB = 20
MAX_IMAGE_WIDTH = 1024
MAX_IMAGE_HEIGHT = 1024
REQUESTS_PLAN = {
  0: 40,  1: 40,  2: 40,  3: 40,  4: 40,  5: 40,  
  6: 55,  7: 55,  8: 55,  
  9: 74,  10: 74,  11: 74,  
  12: 78,  13: 78,  14: 78,  
  15: 78,  16: 78,  17: 78,  
  18: 74,  19: 74,  20: 74,  
  21: 58,  22: 58,  23: 58
}
CUISINE_TYPES = [
    "Global", "Acadian", "Afghan", "African Great Lakes", "Albanian", "American",
    "Andalusian", "Andean", "Angolan", "Argentinian", "Argentinian-Italian",
    "Armenian", "Aostan", "Ashkenazi Jewish", "Australian", "Austrian",
    "Balkan", "Balkan Jewish", "Bangladeshi", "Basque", "Belarusian",
    "Belgian", "Bashkir", "Bolivian", "Botswana", "Brazilian", "British",
    "British-American", "Bruneian", "Buryatian", "Bulgarian", "Burmese",
    "Cameroonian", "Canadian", "Cape Verdean", "Caribbean", "Cajun",
    "Cantonese", "Canarese", "Catalan", "Central American", "Central Asian",
    "Chadian", "Chaoshan", "Chilean", "Chinese", "Chinese American",
    "Chinese Indonesian", "Chinese Peruvian", "Crimean Tatar", "Croatian",
    "Cuban", "Cypriot", "Czech", "Danish", "Djiboutian", "Dominican",
    "Dutch", "Ecuadorian", "Egyptian", "English", "English-American",
    "Eritrean", "Estonian", "Ethiopian", "European", "Fijian", "Filipino",
    "Finnish", "French", "French-American", "French-Canadian", "French-Swiss",
    "Fujian", "Gagauz", "Gambian", "Georgian", "German", "German-American",
    "Greek", "Grenadian", "Guatemalan", "Guyanese", "Haitian", "Hausa",
    "Hawaiian", "Hungarian", "Icelandic", "Igbo", "Indian", "Indian Subcontinent",
    "Indonesian", "Iranian", "Iraqi", "Irish", "Israeli", "Italian",
    "Italian-American", "Ivorian", "Jamaican", "Japanese", "Jewish",
    "Jordanian", "Kashmiri", "Kazakh", "Kenyan", "Korean", "Kurdish",
    "Latin American", "Latvian", "Lebanese", "Libyan", "Lithuanian",
    "Louisiana Creole", "Luxembourgish", "Macedonian", "Macanese", "Madagascan",
    "Maharashtrian", "Malian", "Malawian", "Malaysian", "Maltese",
    "Mediterranean", "Mexican", "Mexican-American", "Middle Eastern",
    "Moldovan", "Mongolian", "Moroccan", "Namibian", "Native American",
    "Nepalese", "New Zealand", "Nicaraguan", "Nigerian", "North American",
    "North Macedonian", "Norwegian", "Ottoman", "Oaxacan", "Pakistani",
    "Palestinian", "Paraguayan", "Peruvian", "Persian", "Polish", "Portuguese",
    "Portuguese-American", "Puerto Rican", "Punjabi", "Québec", "Romanian",
    "Russian", "Shaanxi", "Scottish", "Scandinavian", "Senegalese",
    "Serbian", "Seychellois", "Sicilian", "Singaporean", "Slavic",
    "Slovak", "Slovenian", "Somalian", "South African", "South American",
    "South Asian", "South Australian", "South East Asian", "South Korean",
    "Spanish", "Spanish-American", "Sri Lankan", "Sudanese", "Surinamese",
    "Swahili", "Swedish", "Swiss", "Syrian", "Taichung", "Tajik", "Tamil",
    "Tanzanian", "Texan", "Tex-Mex", "Thai", "Tibetan", "Tunisian",
    "Turkish", "Turkish-American", "Ukrainian", "Uzbek", "Venezuelan",
    "Vietnamese", "West African", "Welsh", "Western Saharan", "Yemenite Jewish",
    "Yemeni", "Yoruba", "Zambian", "Zimbabwean", "Zarma", "Songhai"
]
MEAL_TYPE = [
  "Default",
  "Breakfast",
  "Brunch",
  "Lunch",
  "Dinner",
  "Snack",
  "Appetizer / Starter",
  "Dessert",
  "Side Dish",
  "Soup",
  "Salad",
  "Smoothie",
  "Baking / Pastry",
  "Kid-friendly",
  "Party / Sharing Platter"
]
ALLERGENS = [
  "None",
  "Wheat",
  "Barley",
  "Rye",
  "Oats",
  "Spelt",
  "Kamut",
  "Triticale",
  "Gluten",
  "Cow’s Milk",
  "Goat’s Milk",
  "Sheep’s Milk",
  "Lactose",
  "Casein",
  "Whey",
  "Eggs (Chicken)",
  "Eggs (Duck)",
  "Peanuts",
  "Almonds",
  "Walnuts",
  "Cashews",
  "Pecans",
  "Pistachios",
  "Hazelnuts",
  "Macadamia nuts",
  "Brazil nuts",
  "Pine nuts",
  "Sesame seeds",
  "Poppy seeds",
  "Sunflower seeds",
  "Chia seeds",
  "Flaxseeds",
  "Fish",
  "Salmon",
  "Tuna",
  "Cod",
  "Shellfish",
  "Shrimp",
  "Crab",
  "Lobster",
  "Mollusks",
  "Squid",
  "Scallops",
  "Soy",
  "Lupin",
  "Lentils",
  "Chickpeas",
  "Beans",
  "Green peas",
  "Mustard",
  "Sulfites"
]
DIETARY_PREFENCES = [
  "Default",  
  "Vegan",
  "Vegetarian",
  "Pescatarian",
  "Flexitarian",
  "Omnivore",
  "Raw Food",
  "Whole30",
  "Paleo",
  "Keto",
  "Low-Carb",
  "High-Protein",
  "Low-Fat",
  "Low-Sodium",
  "Low-Sugar",
  "No Added Sugar",
  "DASH Diet",
  "Mediterranean Diet",
  "Diabetic-Friendly",
  "Heart-Healthy",
  "Anti-Inflammatory",
  "Gluten-Free",
  "Dairy-Free",
  "Lactose-Free",
  "Nut-Free",
  "Soy-Free",
  "Egg-Free",
  "Shellfish-Free",
  "Halal",
  "Kosher",
  "Ayurvedic",
  "Macrobiotic",
  "FODMAP-Friendly",
  "Sattvic Diet",
  "Alkaline Diet"
]